const assert = require('node:assert/strict')
const vanilla = require('zustand/vanilla')
const { createZusound, version, zusound } = require('zusound')

const createStore = vanilla.createStore ?? vanilla.default ?? vanilla
const store = createStore(zusound(() => ({ count: 0 }), { enabled: true }))
store.setState({ count: 1 })
assert.equal(store.getState().count, 1)
assert.equal(typeof store.zusoundCleanup, 'function')
store.zusoundCleanup()
store.zusoundCleanup()
const instance = createZusound({ enabled: true })
const unsubscribe = store.subscribe(instance)
store.setState({ count: 2 })
unsubscribe()
instance.cleanup()
assert.equal(store.getState().count, 2)
assert.match(version, /^\d+\.\d+\.\d+/)
console.log('CommonJS require, SSR updates and cleanup passed')
